### ISSUE TITLE
支持@Configuration下的bean实时Refresh吗？

### ISSUE THREAD

**Issue by luaifei** [Code2Life/spring-boot-dynamic-config#3]
如题

**Comment by Code2Life** [comment]
对于Spring来说， @Configuration 注解并没有起实际的作用的，起作用的是 @ConfigurationProperties @Value 这两个注解。 

这个库是支持在  @ConfigurationProperties 或 @Value 的 类/方法 上加@DynamicConfig 实现实时刷新。

**Comment by luaifei** [comment]
好的，从2.4版本开始，SpringBoot出了一个[`spring.cofig.import`](https://docs.spring.io/spring-boot/docs/2.5.7/reference/htmlsingle/#features.external-config.files.configtree)配置方式，比`spring.cofig.location`更友好和强大，这边可以增加支持吗？

**Comment by Code2Life** [comment]
很棒的提议，我研究一下

**Comment by luaifei** [comment]
谢谢，还有一个建议，目前`@DynamicConfig`注解可以添加到`@Component`和`@ConfigurationProperties`。但还有一种场景是ConfigurationProperties是由其它Starter提供的，例如spring.datasource等相关配置，如何增加对这类Bean的热刷新呢？我想到是否可以增加一种方式，自定义返回所有需要热刷新的Bean的Class？目前想到的一个方法是暴露一个注册器的Bean，然后调用这个Bean增加用户感兴趣的Bean，这样需要刷新的bean就可以来自于三个来源。

**Comment by Code2Life** [comment]
这个情况考虑过，但不太好处理，因为即使动态改了Bean的属性，一些资源可能已经建立过了，无法实现预期效果。所以Spring Cloud的行为其实是整个Bean都完全重建了。

**Comment by Code2Life** [comment]
@luaifei 
最新的1.0.9版本已经支持了 spring.config.import

https://github.com/Code2Life/spring-boot-dynamic-config#import-config-tree
