### ISSUE TITLE
成功启动了example，在application-another-profile.yml修改配置，页面没有变化

### ISSUE THREAD

**Issue by y9ng** [Code2Life/spring-boot-dynamic-config#5]
没有达到动图的效果，也没有改example的代码，用f12查看了请求，每次获取的还是启动前的值，我是哪一步出了问题。。

**Comment by Code2Life** [comment]
Run Config的Arguments里面要加上 --spring.config.location=src/main/resources/  启动

**Comment by y9ng** [comment]
> Run Config的Arguments里面要加上 --spring.config.location=src/main/resources/ 启动

好的，谢谢回复
